version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'

  gobtcapp:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 10 && ./server"
    ports:
      - '8080:8080'